# Generated by Django 5.0.1 on 2024-02-06 16:06

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0003_alter_product_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.IntegerField(validators=[API.models.validate_product_cost]),
        ),
    ]
